export const FETCHING_REQUESTED = 'FETCHING_FRIENDS_REQUESTED';
export const FETCHING_FAILED = 'FETCHING_FRIENDS_FAILED';
export const FETCHING_SUCCEDED = 'FETCHING_FRIENDS_SUCCEDED';

export const FETCHING_MORE_REQUESTED = 'FETCHING_MORE_FRIENDS_REQUESTED';
export const FETCHING_MORE_FAILED = 'FETCHING_MORE_FRIENDS_FAILED';
export const FETCHING_MORE_SUCCEDED = 'FETCHING_MORE_FRIENDS_SUCCEDED';